export const GLOBAL_PREFIX = 'api';

export const ENV_VARIABLE_NAMES = {
  ACCESS_TOKEN_EXPIRATION_TIME: 'ACCESS_TOKEN_EXPIRATION_TIME',
  API_REQUEST_MAXIMUM_LIMIT: 'API_REQUEST_MAXIMUM_LIMIT',
  API_REQUEST_TIME_TO_LIVE: 'API_REQUEST_TIME_TO_LIVE',
  EMAIL_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS:
    'EMAIL_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS',
  EMAIL_BLOG_PLATFORM: 'EMAIL_BLOG_PLATFORM',
  EMAIL_BLOG_PLATFORM_PASSWORD: 'EMAIL_BLOG_PLATFORM_PASSWORD',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
  INCLUDE_TESTING_MODULE: 'INCLUDE_TESTING_MODULE',
  IS_SWAGGER_ENABLED: 'IS_SWAGGER_ENABLED',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  ADMIN_USERNAME: 'ADMIN_USERNAME',
  NODE_ENV: 'NODE_ENV',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  PORT: 'PORT',
  POSTGRESQL_URL: 'POSTGRESQL_URL',
  RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS:
    'RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  SHOULD_SEND_EMAIL: 'SHOULD_SEND_EMAIL',
} as const;

export enum ENVIRONMENTS {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
  TESTING = 'testing',
}

export const DB_TYPE = 'postgres';
export const PG_PORT = 5432;

export const DB_TABLE_NAMES = {
  BLOGS: 'blogs',
  COMMENT_LIKES: 'comment_likes',
  COMMENTS: 'comments',
  DEVICES: 'devices',
  EMAIL_CONFIRMATIONS: 'email_confirmations',
  PASSWORD_RECOVERIES: 'password_recoveries',
  POST_LIKES: 'post_likes',
  POSTS: 'posts',
  USERS: 'users',
};

export const ROUTES = {
  AUTH: 'auth',
  BLOGS: 'blogs',
  COMMENTS: 'comments',
  DEVICES: 'devices',
  LIKE_STATUS: 'like-status',
  LOGIN: 'login',
  LOGOUT: 'logout',
  ME: 'me',
  NEW_PASSWORD: 'new-password',
  PASSWORD_RECOVERY: 'password-recovery',
  POSTS: 'posts',
  REFRESH_TOKEN: 'refresh-token',
  REGISTRATION: 'registration',
  REGISTRATION_CONFIRMATION: 'registration-confirmation',
  REGISTRATION_EMAIL_RESENDING: 'registration-email-resending',
  SECURITY: 'security',
  USERS: 'users',
};
