name: "npm install with cache"
description: "Install dependencies using npm with store caching"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm' 

    - name: Install Dependencies
      shell: bash
      run: npm ci