name: Run Tests Workflow

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
    workflow_call:

jobs:
    test:
        name: Test Suite
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: george
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: TypeORMBloggerPlatform_Test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U george -d TypeORMBloggerPlatform_Test"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=10

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install deps
              uses: ./.github/actions/cache-npm-install

            - name: Run migrations
              run: npm run migration:run:test 

            - name: Run tests
              run: npm run test:e2e
